import React, { useEffect, useRef, useState } from 'react';
import { CornerDownLeft, Mic, MicOff, Search, Sparkles } from 'lucide-react';
import { getSearchSuggestions } from '../services/api.js';
export default function SearchBar({onSearch,loading,initial=''}){
 const [query,setQuery]=useState(initial); const [listening,setListening]=useState(false); const [suggestions,setSuggestions]=useState([]); const [open,setOpen]=useState(false); const [active,setActive]=useState(-1); const recognition=useRef(); const shell=useRef();
 useEffect(()=>setQuery(initial),[initial]);
 useEffect(()=>{const close=(event)=>!shell.current?.contains(event.target)&&setOpen(false);document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 useEffect(()=>{if(query.trim().length<2){setSuggestions([]);setOpen(false);return}const timer=setTimeout(async()=>{try{const items=await getSearchSuggestions(query);setSuggestions(items);setOpen(items.length>0);setActive(-1)}catch{setSuggestions([])}},220);return()=>clearTimeout(timer)},[query]);
 const voice=()=>{ const Speech=window.SpeechRecognition||window.webkitSpeechRecognition; if(!Speech)return; const rec=new Speech(); recognition.current=rec; rec.lang='en-IN'; rec.onstart=()=>setListening(true); rec.onend=()=>setListening(false); rec.onresult=(e)=>setQuery(e.results[0][0].transcript); rec.start(); };
 const choose=(item)=>{setQuery(item.query);setOpen(false);onSearch(item.query)};
 const submit=(e)=>{e.preventDefault();if(active>=0&&open)return choose(suggestions[active]);if(query.trim()){setOpen(false);onSearch(query.trim())}};
 const keys=(e)=>{if(!open)return;if(e.key==='ArrowDown'){e.preventDefault();setActive(i=>(i+1)%suggestions.length)}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>(i<=0?suggestions.length-1:i-1))}if(e.key==='Escape')setOpen(false)};
 const voiceSupported=typeof window!=='undefined'&&Boolean(window.SpeechRecognition||window.webkitSpeechRecognition);
 const highlight=(label)=>{const index=label.toLowerCase().indexOf(query.toLowerCase());if(index<0)return label;return <>{label.slice(0,index)}<strong>{label.slice(index,index+query.length)}</strong>{label.slice(index+query.length)}</>};
 return <div className="autocomplete" ref={shell}><form className={`search-shell ${open?'suggestions-open':''}`} onSubmit={submit}><Sparkles className="spark"/><input role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls="search-suggestions" aria-activedescendant={active>=0?`suggestion-${active}`:undefined} aria-label="Describe the government service you need" value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>suggestions.length&&setOpen(true)} onKeyDown={keys} placeholder="Try: renew my licence, check PF balance, book a train..." autoComplete="off"/>{voiceSupported&&<button className="icon-btn" type="button" onClick={voice} aria-label="Search by voice">{listening?<MicOff/>:<Mic/>}</button>}<button className="search-btn" disabled={loading||!query.trim()}><Search/> <span>Search</span></button></form>{open&&<div className="autocomplete-menu" id="search-suggestions" role="listbox"><p className="suggestion-label">Related searches</p>{suggestions.map((item,index)=><button type="button" id={`suggestion-${index}`} role="option" aria-selected={active===index} className={active===index?'active':''} key={`${item.label}-${item.portalName}`} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(item)} onMouseEnter={()=>setActive(index)}><Search/><span><b>{highlight(item.label)}</b><small>{item.portalName} · {item.category}</small></span><CornerDownLeft/></button>)}</div>}</div>
}
