import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App.jsx';
import './styles.css';
import './modal.css';
import './result-guidance.css';
import './autocomplete.css';
import './action-buttons.css';
import './india-theme.css';
import './languages.css';
import './language-selector.css';
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
